export const actiontypes = {
    ADD_GAMES_TO_PLAY : 'ADD_GAMES_TO_PLAY',
    ADD_GAMES_PLAYED : 'ADD_GAMES_PLAYED',
    MOVE_GAMES_TO_PLAYLIST: 'MOVE_GAMES_TO_PLAYLIST',
    REMOVE_GAMES_FROM_PLAYLIST: 'REMOVE_GAMES_FROM_PLAYLIST',
    REMOVE_GAMES_FROM_PLAYED:'REMOVE_GAMES_FROM_PLAYED',
}